services:
  minio:
    image: minio/minio
    container_name: minio
    command: "server /data --console-address \":9001\""
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio/:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgis:
    image: postgis/postgis
    container_name: bike-beacon-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  bike_beacon_server:
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      postgis:
        condition: service_healthy
      minio:
        condition: service_healthy

